### ISSUE TITLE
xcaddy in 2.6.3 breaks because of golang issue for all plugins / modules unless modules updated by maintainer

### ISSUE THREAD

**Issue by sam-agnew-pqs** [caddy-dns/godaddy#4]
Caddy 2.6.3 is out but building it with the godaddy-dns module (affects many modules apparently) fails unless the module is updated.

Caddy dev [francislavoie](https://github.com/francislavoie) details the issue near the bottom of issue https://github.com/golang/go/issues/56494

Linked is https://github.com/quic-go/quic-go/issues/3652

Unfortunately, I'm not a Go dev. Just someone trying to update Caddy to 2.6.3 and depending upon the godaddy-dns plugin..

Raising this in the hopes that a plugin update can fix this

**Comment by mario-moreira** [comment]
I have the same problem.
